#!/bin/sh

#######################################################
#
# Add here the commands to be excuted after the package
# has been installed
#

#Example: create some symbolic links
#
#chown -R ${user}:${group} /opt/${appName}-${appVersion}
#ln -s /opt/${appName}-${appVersion} /opt/${appName}

echo ${appName}-${appVersion} installed

